### ISSUE TITLE
[Bug]: Picard run out of space on device

### ISSUE THREAD

**Issue by marinafloresp** [ejh243/BrainFANS#260]
### What happened?

Picard is a software used multiple times in the ATAC-seq pipeline to mark duplicated reads (Step 1.3 and 6.1) or add read groups (Step 6.1). For large samples, these processes are memory and resources intensive such that a temporary directory with large capacity is needed. This is not always the case of the shared temporary space allocated when a job is submitted by ISCA. Even if an alternative temporary directory is specified in the .bashrc file, this is not used by the Picard software and the processes can't be completed. 

### How can the bug be reproduced?

This happens both when using Picard from a conda environment and from the software source file. 

### Relevant log output

```shell
Exception in thread "main" picard.PicardException: Exception writing ReadEnds to file.
	at picard.sam.markduplicates.util.ReadEndsForMarkDuplicatesCodec.encode(ReadEndsForMarkDuplicatesCodec.java:74)
	at picard.sam.markduplicates.util.ReadEndsForMarkDuplicatesCodec.encode(ReadEndsForMarkDuplicatesCodec.java:32)
	at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:254)
	at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:182)
	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:627)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:270)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:309)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
	Suppressed: java.io.IOException: No space left on device
		at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
		at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
		at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132)
		at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:97)
		at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:67)
		at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:288)
		at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
		at java.base/java.nio.channels.Channels.writeFully(Channels.java:96)
		at java.base/java.nio.channels.Channels$1.write(Channels.java:171)
		at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
		at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
		at org.xerial.snappy.SnappyOutputStream.dumpOutput(SnappyOutputStream.java:360)
		at org.xerial.snappy.SnappyOutputStream.compressInput(SnappyOutputStream.java:377)
		at org.xerial.snappy.SnappyOutputStream.flush(SnappyOutputStream.java:334)
		at org.xerial.snappy.SnappyOutputStream.close(SnappyOutputStream.java:419)
		at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:259)
		... 6 more
Caused by: java.io.IOException: No space left on device
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:97)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:67)
	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:288)
	at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
	at java.base/java.nio.channels.Channels.writeFully(Channels.java:96)
	at java.base/java.nio.channels.Channels$1.write(Channels.java:171)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
	at org.xerial.snappy.SnappyOutputStream.dumpOutput(SnappyOutputStream.java:360)
	at org.xerial.snappy.SnappyOutputStream.compressInput(SnappyOutputStream.java:377)
	at org.xerial.snappy.SnappyOutputStream.write(SnappyOutputStream.java:130)
	at java.base/java.io.DataOutputStream.writeInt(DataOutputStream.java:208)
	at picard.sam.markduplicates.util.ReadEndsForMarkDuplicatesCodec.encode(ReadEndsForMarkDuplicatesCodec.java:60)
	... 8 more
```

**Comment by marinafloresp** [comment]
This has been solved
